name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:

  static-analysis:
    if: github.repository != 'mattdeform/MayaPythonProjectTemplate'
    uses: ./.github/workflows/reusable-static-analysis.yml

  tests:
    if: github.repository != 'mattdeform/MayaPythonProjectTemplate'
    uses: ./.github/workflows/reusable-maya-tests.yml
