name: build and deploy docs

on:
  workflow_dispatch:  # Manual trigger
  workflow_call:
permissions:
  contents: write

jobs:
  build-and-deploy-docs:
    # only build docs when publishing a release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - run: |
          pip install mkdocs-material mkdocstrings[python]
          mkdocs gh-deploy --force