name: maya tests

on:
  workflow_call:
  workflow_dispatch:  # Manual trigger

jobs:
  collect_tests:
    runs-on: ubuntu-latest
    outputs:
      tests_collected: ${{ steps.check_tests.outputs.tests_collected }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Check for tests
        id: check_tests
        run: |
          #!/bin/bash
          set +e  # Disable exit on error
          pytest --collect-only
          exit_code=$?
          set -e  # Re-enable exit on error
          
          if [ $exit_code -eq 5 ]; then
            echo "tests_collected=0" >> $GITHUB_OUTPUT
            echo "No tests were collected."
          else
            collected=$(pytest --collect-only | grep -oP 'collected \K\d+')
            echo "tests_collected=$collected" >> $GITHUB_OUTPUT
            echo "Collected $collected tests."
          fi

  no_tests_found:
    needs: collect_tests
    if: needs.collect_tests.outputs.tests_collected == '0'
    runs-on: ubuntu-latest
    steps:
      - name: No tests found
        run: echo "No tests were collected. Skipping test execution."


  maya:
    needs: collect_tests
    if: needs.collect_tests.outputs.tests_collected != '0'
    runs-on: ubuntu-latest

    strategy:

      fail-fast: false

      matrix:
        # add or remove versions as needed, a job per version will be created
        # supported tags here: https://github.com/mottosso/docker-maya/
        maya_version: ["2024",]

    container: mottosso/maya:${{ matrix.maya_version }}  # ty mottosso!

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          mayapy -m pip install --upgrade pip
          mayapy -m pip install pip-tools
          pip-compile requirements.in
          pip-compile requirements-test.in
          mayapy -m pip install --user -r requirements-test.txt

      - name: Set Maya environment variables
        run: |
          export XDG_RUNTIME_DIR=/var/tmp/runtime-root
          export MAYA_DISABLE_ADP=1

      - name: Run tests
        run:  mayapy -m pytest tests
